### ISSUE TITLE
Dates are Incorrect

### ISSUE THREAD

**Issue by Taien** [NyaaPantsu/nyaa#1038]
I've noticed and verified that the dates being shown on the results page are incorrect.  They are all the same identical time, and it appears to be the current time, not the time the file was uploaded.  See this pic:  
![image](https://user-images.githubusercontent.com/1469026/27357787-3d9c41f4-55d9-11e7-93ab-589a4c505277.png)

It's hard to tell here, but the date shown for every result is identical (including the time, down to the second), which can't possibly be right.  It may just be a visual error though, like you're using GETDATE() in your SQL query instead of the date column from the upload.

**Comment by Taien** [comment]
And yes, refreshing the page changes the dates to the new (current) time.

**Comment by akuma06** [comment]
Is it not the scrapper which upload the torrents with the same date?

**Comment by Taien** [comment]
No because if you refresh the page, the time changes.  It's always reflective of the current time, not an upload time.

**Comment by akuma06** [comment]
I'm sorry but I can't see what you mean, when I go here : https://nyaa.pantsu.cat/search/5 I have different dates. And when I hover the dates on home page I get those results for the first three torrents: "21:21:00Z", "21:20:04Z" and "21:46:00Z".
They are not in order (fixed in dev) but they are different, can you confirm that the dates are not different to you? If they aren't, can you give your Browser version

**Comment by akuma06** [comment]
However we are using javascript to convert server time to your local time. So it is normal that the date when you hover and the date shown are not the same

**Comment by Taien** [comment]
When I get a chance I'll refresh cache and try again, maybe you fixed it
already

**Comment by akuma06** [comment]
After a report on irc from Wario, it seems Sukebei has the bug.
From what I can gather, the dates are right on view page and are not in search pages. Since view page gets its data from PG, the dates are in database. However, the search pages get their dates from ES and, taking into account that we are on the same go build and that nyaa doesn't have the issue, it seems that ES doesn't store the dates for sukebei.

We might need tomleb to look into it
