### ISSUE TITLE
Major refactor

### ISSUE THREAD

**Issue by ewhal** [NyaaPantsu/nyaa#1072]
Move to the following project structurre
```
controllers (Pretty much routes)
main.go
db
models (For all db related stuff)
public 
templates
translations
utils 
```
https://github.com/jinzhu/configor
https://github.com/tdewolff/minify
LRU cache for db results
External package for form validation?
Optimize queries
Possibly use gin to reduce needed code further?
Write api documentation

**Comment by akuma06** [comment]
I don't know though. I like services, they are really useful to use in controllers. It helps to not have duplicated codes in it and separe them from other pieces of code by being in their own packages. I think of them as the link between a controller and its model.

Why I didn't put everything in model then? Which should be the the link in MVC architecture, it is due to import cyclic error of golang. Golang tends to have packages really huge. But that makes code less maintenable and less understandable, since you might lose time to find where is the function. you search. Just try on gin-gonic repo to find the allocateContext function. 

Anyway between too large packages which you have to import each time for only one or two files in it and small packages with services, I would rather go for the latter.

However, we can try to make fuse utils and services and rename it as utils or something else.

By the way, I already tried to seperate models in directory for each model and import the services in those directory.  However we have then an import cyclic thing between the models. For example, Comments import torrents which import comments...
