### ISSUE TITLE
New issues since refactor

### ISSUE THREAD

**Issue by sfan5** [NyaaPantsu/nyaa#1267]
* search box is short(er than before) / no longer expands
* menubar overlapping in modpanel
![bildschirmfoto_2017-07-22_18-34-19](https://user-images.githubusercontent.com/1042418/28492930-8177c442-6f0c-11e7-9ec0-f73e565d47a6.png)
* broken html on reassign page
![bildschirmfoto_2017-07-22_18-34-19_2](https://user-images.githubusercontent.com/1042418/28492934-97d11f04-6f0c-11e7-8abe-604aa261a1a0.png)
* comment usernames don't link to user page
* torrent reports for non-existing torrents (?)
![bildschirmfoto_2017-07-22_18-39-26](https://user-images.githubusercontent.com/1042418/28492965-77ed800a-6f0d-11e7-9b21-68bd93dcaf79.png)
* moderation panel html title missing space `Nyaa PantsuModeration Panel - Reports List`
* upload preview shows "0 B" instead of "Unknown" for filesize
* js for switching disable between magnet input & file input no longer present on upload page

**Comment by yiiTT** [comment]
unable to delete torrent reports

**Comment by sfan5** [comment]
mod tools box has white bg in dark theme mode

**Comment by sfan5** [comment]
logging out from modpanel results in 404 (redirects back to `/mod/`)

**Comment by sfan5** [comment]
![bildschirmfoto_2017-07-29_14-24-04](https://user-images.githubusercontent.com/1042418/28744992-198c656a-746e-11e7-8c20-017d828f0285.png)

**Comment by akuma06** [comment]
* Search input expandable has been removed since it was hard for user to click on "search" button
* Admin Menu: fix #1398
* Commentlist: fix #1398
* broken html: fix #1398
* torrent reports for non-existing torrents: might be hentai torrents deleted by sql query?
* Missing space fixed
* recent comments: fix #1398
* Upload preview: fix #1398
* JS Switch: fix #1398
* ModTools background: fix #1398
* Logging out from modpanel redirect to "/" now (#1398)
