### ISSUE TITLE
Torrent file not found page broken

### ISSUE THREAD

**Issue by Kiloutre** [NyaaPantsu/nyaa#1582]
It breaks when the variable `magnet` is called
Strangely enough it works on dev
https://dev.pantsu.cat/download/33E6132C1D1AD49D4632AF9543D32EEA30073E9F
https://nyaa.pantsu.cat/download/33E6132C1D1AD49D4632AF9543D32EEA30073E9F

**Comment by akuma06** [comment]
It doesn't work because "magnet" variable is not accessible in the scope. Since you don't add magnet variable in each case. (if the torrent is not in db, you display the torrent_file_missing without magnet variable, ...)
If you go to this url: https://dev.pantsu.cat/download/33E6132C1D1AD49D4632AF9543D32EEA30073E9 the page is also broken.
You have to check that magnet variable is set before checking that it is not empty. I told you that when you asked for it.
templates/errors/torrent_file_missing.jet.html
```
{{ if isset(magnet) && magnet != "" }}
```
