### ISSUE TITLE
Sukebei changes proposal

### ISSUE THREAD

**Issue by yiiTT** [NyaaPantsu/nyaa#173]
* ~~A user should be able to login into one account for nyaa and sukebei.~~
* ~~You should be able to access a users torrents by just changing the subdomain. EX: https://nyaa.pantsu.cat/user/[username/id] -> https://sukebei.pantsu.cat/user/[username/id]~~
* Sukebei's categories should be moved from 1 and 2 to 7 and 8. (while also adding their sub-categories to the main table to keep them unique)
* ~~Torrents for nyaa and sukebei should be on separate tables, while not have conflicting IDs (EX: start sukebei's ids at 1000000)~~

**Comment by akuma06** [comment]
> A user should be able to login into one account for nyaa and sukebei.
I agree, we just have to share the same user table. Nothing to change

> You should be able to access a users torrents by just changing the subdomain. 
As long as the same user database is shared, there is nothing to change

> Sukebei's categories should be moved from 1 and 2 to 7 and 8.
Don't know what you meant

> Torrents for nyaa and sukebei should be on separate tables, while not have conflicting IDs (EX: start sukebei's ids at 1000000)
Separate tables : yes, absolutely. But having conflicting Id's do not matter. As long as they are on different tables

**Comment by yiiTT** [comment]
> > Sukebei's categories should be moved from 1 and 2 to 7 and 8.

> Don't know what you meant

Currently sukebei's categories are 1 (anime) 2 (literature), where from before they were 7 (Art) 8 (Real Life) which also messes up by displaying the incorrect category image.

**Comment by egozi44** [comment]
Also Sukebei seem to be completely broken compared to pantsu, the switch button may switch to it but won't always inform you of it (I assume it because you keep develop the site), the night button not works (already been reported), both sites (mostly Sukebei ) will be overloaded, the bookmark I made take me back to pantsu and not Sukebei... I can easily loose the different between the two since they seem to keep to switch to each other when one is overlarded (hope the overlord issue won't stay like that as original nyaa was full of active users).

 One last thing... it seem that no one upload anything despite having upload button... is the site blocking anyone or you still not ready to let others upload till you finish the job?

**Comment by yiiTT** [comment]
@egozi44 sukebei has been put on hold with an older verion but it is starting to get worked on so most of the interface issues will get fixed soon.

Also torrents that are listed with the date being "1 of January 1970" were imported automatically from someone who had a lot of the missing sukebei torrents which is why they are missing the date. I think it was about 20k torrents that were imported.

**Comment by egozi44** [comment]
I see 

hope that a sign you get some of the updated database back :9

**Comment by sora-chan** [comment]
> EX: start sukebei's ids at 1000000

That's a retardedly bad idea. What happens when nyaa torrent IDs reach 1000000?

The whole nyaa/sukebei backend seperation is completely retarded in the first place.

**Comment by yiiTT** [comment]
@sora-chan Looks like sukebei's IDs will be keeping on their current track on https://sukebei.pantsu.cat/
Also the torrents + comments for nyaa and sukebei are on separate tables in the database with shared users.
