### ISSUE TITLE
Username can't contain non-ascii characters

### ISSUE THREAD

**Issue by tomleb** [NyaaPantsu/nyaa#219]
Someone is receiving "Username contains  illegal characters" when trying to create an account with a username containing non-ascii characters.

**Comment by ayame-git** [comment]
Unicode is globalism

**Comment by yiiTT** [comment]
This needs to be addressed, there are old usernames that are html entity encoded like "ヽ&#40;´ー&#96;&#41;ノ", "Avallac&#39;h", "&#40;_KoDAk_&#41;".

**Comment by KuroiKitsu** [comment]
@yiiTT you forgot `&#xff59;&#xff49;&#xff49;&#x0422;&#x0422;`.

**Comment by maj160** [comment]
This is caused by USERNAME_REGEX on line 10 of service/user/form/formValidator.go
The question is, what should be an illegal character in this context? Currently it's anything that isn't [a-zA-Z0-9_], but clearly we should change that.

What about changing it to `\s` to ban whitespace but allow all other characters? Is that too generous?

Also, we should make sure we don't cause any Stored XSS vulnerabilites - Check that we're properly escaping usernames wherever they're being displayed.

**Comment by yiiTT** [comment]
@KuroiKitsu I don't have that user in my database hmm?

**Comment by KuroiKitsu** [comment]
@yiiTT What I mean is to not add support for arbitrary unicode characters before report/moderation-related features.

Or at least do the "unique" checking on a normalized version of the user names.

Otherwise you could have a bunch of usernames that all look like `HorribleSubs`, for example.

**Comment by akuma06** [comment]
`/^(?:[\p{L}\p{Mn}\p{Pd}\'\x{2019}]+\s[\p{L}\p{Mn}\p{Pd}\'\x{2019}]+\s?)+$/u

Might fix the issue (Stackoverflow)

**Comment by yiiTT** [comment]
After having a week to think about this, I feel that the current allowed characters are fine.
