### ISSUE TITLE
Search Index

### ISSUE THREAD

**Issue by GRMrGecko** [NyaaPantsu/nyaa#341]
If you find search to be slow with PostgreSQL, it may be worth considering a search indexer like ElasticSearch (https://www.elastic.co/products/elasticsearch). I use it in one of my projects, and it works amazingly. You can either use the JSON API or a GoLang library such as https://github.com/olivere/elastic/

**Comment by majestrate** [comment]
i keep saying this but no one listens ;~;

**Comment by LostStranger** [comment]
You can try implementing yourself maybe, because this project only has a limited core dev working on core features. I understand that indexing efficiency is an important matter but there are still core features that are yet to be implemented, maybe after they finish all the main essential feature they can start visitng this again.

**Comment by yiiTT** [comment]
Getting close to ES implementation. Will reference when there is an update.
