### ISSUE TITLE
RSS download Japanese filename text garbled

### ISSUE THREAD

**Issue by hinatayuusuke** [NyaaPantsu/nyaa#443]
When I use BitTorrent RSS feed get list, and from list direct DL , Japanese filename text just garbled.
is this a bug? or I can just change BitTorrent setting to avoid text  garbled?

**Comment by mitki** [comment]
It's most likely a system locale issue, client side. 

Is there any setting to change character encoding on BitTorrent?

**Comment by S0X-LT** [comment]
You shouldn't be using BitTorrent in the first place because it is a big security risk to yourself and other peers. And because it is an Ad-ridden mess. Use [qBittorrent ](https://www.qbittorrent.org/) or Deluge on Windows, and Transmission on MAC/Linux

Anyways, the problem is likely because of your system locale and has nothing to do with the site. Try to download a torrent with CJK characters in it from another site and if it displays them correctly, we'll look into it.

**Comment by akuma06** [comment]
And if you can provide a screenshot, it would also be nice. We can't reproduce the bug (if any) without much information (OS version, bittorent version, your locale...)

**Comment by hinatayuusuke** [comment]
Thanks your reply. and sorry information wasn't enough.
also I tried qbittorrent, qbittorrent didn't have this problem.

below is my system information and reproduce step
OS: win7 JP 64bit 
bittorrent version :7.10
locale : Japanese

reproduce step

use Nyaa's RSS and copy the URL to Bittorrent RSS feed, then from Bittorrent's RSS list download Japanese name file.
[
![default](https://cloud.githubusercontent.com/assets/28677532/26032071/fae70dca-38c4-11e7-8551-6b4017d96169.jpg)
![2](https://cloud.githubusercontent.com/assets/28677532/26032073/fec9c5e0-38c4-11e7-8922-3fdb744db73f.jpg)

](url)

**Comment by ewhal** [comment]
Has this been resolved?

**Comment by FevLoad** [comment]
there is a problem with the RSS feed, direct download does not work for .torrent files
please update them with the magnet links so it can be work
