### ISSUE TITLE
Dates and timezones and annoying shit

### ISSUE THREAD

**Issue by dumbwanker** [NyaaPantsu/nyaa#534]
Torrent creation date is a bit confusing right now, due to timezone stuff. It's not clear which one is being used

Ideas:
* Specify the timezone being used currently, with a (UTC/GMT +/-) next to it
* Use UTC time as standard and make it clear that UTC is being used
* Convert time into local time based on the user's location, and make it clear this is the case (? - Bad idea)

thoughts?

**Comment by loadletter** [comment]
"date time UTC" like nyaa.se seems the best, localtime converstion could always be added later as javascript

**Comment by sfan5** [comment]
The code writes some sort of standardized time format into the HTML and JS will convert it to localtime and change how it's displayed.
That's the current state, however it's kinda broken as the server seems to pretend UTC+2(?) is the same as UTC which is why dates are 2 hours off... (or does that depend on some setting?)

**Comment by dumbwanker** [comment]
Ah, that makes sense. I'm in UTC+1 and the time given in the HTML `title` attribute is one hour behind the time that's being displayed

Thanks for the clarification!
