### ISSUE TITLE
Pressing either "name" "S" "L" "D" "date" "size" should return the sorting back to it's normal value

### ISSUE THREAD

**Issue by nakedloli** [NyaaPantsu/nyaa#546]
At the moment there's no way of making them normal so it's always stuck on ascending and descending" @SpamNeko 

https://puu.sh/vRKzL/8178355001.png

**Comment by SpamNeko** [comment]
In actuality all searches are always sorted by something asc or desc (a blank search, e.g. the home page, is sorted by ID desc). The sorting doesn't show up on the arrows both because ID isn't a column in the table, and because the sorting isn't specified in the query string.

Sorting by date and ID are basically the same thing since IDs increase monotonically (they should anyway) as do dates (time travelers notwithstanding), so I'll change it tomorrow to show the sorting as Date desc on the frontend if no other sorting is specified.

Also means you won't have to click Date twice to reverse the default ordering.
