### ISSUE TITLE
Implement a Torznab Compatible API

### ISSUE THREAD

**Issue by CodeMonkey626** [NyaaPantsu/nyaa#607]
I would be great if nyaa.pantsu.cat could add a Torznab compatible API to query for torrents.

This would allow for direct integration with software such as Sonarr and Radarr as well ensuring applications don't need to resort to scraping to search for indexed torrents.

Background on Sonarr:

> Sonarr is a PVR for Usenet and BitTorrent users. It can monitor multiple RSS feeds for new episodes of your favorite shows and will grab, sort and rename them. It can also be configured to automatically upgrade the quality of files already downloaded when a better quality format becomes available.

Background on Torznab:

> The Newznab api specification is built around a simple rss feed with filtering and paging capabilities. It was designed for usenet primarily, but it can be easily adapted for torrents.

Torznab Documentation:
https://github.com/Sonarr/Sonarr/wiki/Implementing-a-Torznab-indexer

I'm not sure if this would be complimentary to or separate from #569

**Comment by yiiTT** [comment]
Sonarr will accept the EZTV RSS Spec which would not take much to implement, just a few changes to our RSS generator and it should be working. 

Where as the Torznab API is like a TV show API (and more) which would require us to deal with the show structures and everything else kinda like Netflix or a Usenet Indexer from my understanding of it.

**Comment by CodeMonkey626** [comment]
@taloth can probably provide more insight here.

https://github.com/nyaadevs/nyaa/issues/18/ is a similar thread but for nyaa.si for some additional context.

**Comment by Taloth** [comment]
If you want just RSS, then using the eztv rss schema is the best option.
However if you want to provide search (full-text OR anidb id+abs nr) in the future, then look into torznab.

Shameless copy/pasta:

The value proposition is: Quite a few apps already know how to talk to this api specification. The spec primary boils down to agreeing on a few standard query params and the format for the rss result so that any client can read it.
This is in contrast with every indexer/site having their own custom rss or api which would require the apps to implement the custom api for each site separately. And there are considerably more sites than apps. 😄

You can start with full-text search, it's fine and handled by the q query param. For tv series the spec normally uses tvdbid, tvmazeid, season and ep. which are simple indexer db lookups.
A couple of months ago I suggested adding anidbid/aid and abs to the list to do the same for the anime absolute format. But this is optional and the ?t=caps response specifies with query params are supported.
If this format can be agreed on, then any client that knows those query params could query anime sites by increasingly efficient query params:

q=Anime+Title+02 (full text)
q=Anime+Title&abs=2 (db column & fulltext/series title)
anidbid=1234&abs=2 (indexed db lookup)

If you have more questions about it, let me know. I didn't go into everything for the sake of brevity.

**Comment by yiiTT** [comment]
Thanks for the insight @Taloth looks like the EZTV RSS schema is the best option for us since we are not linking uploads to anidb.net id's or shows.

Implementing the EZTV RSS spec would be the simplest and most effective option right now. There was some talks about linking torrent uploads to AID and other databases but I don't expect that happening at this current time.

**Comment by CodeMonkey626** [comment]
Linking to AniDB isn't required for this. The EZTV schema only you gets you half the way there for PVR support.

I'll give you a concrete example.

If I add a new show to my PVR that just started airing, the PVR can pull the RSS feed periodically looking for new episodes for that show, and it'll work fine.

But if I add a show that aired last season, this won't work. In that case, the PVR needs to search for the individual episodes in order to download them which it can't do without a adapter written for the specific query mechanics of that individual site.

That's where torznab comes in. It's a standard way of querying for and returning results that PVRs can understand.

**Comment by xelra** [comment]
@yiiTT You don't have to implement all capabilities of the torznab api. If you don't have anidbid or tvdbid, you just leave it out. The great thing is that it can just be added piece by piece later.

The real benefit though is the search. Even if you just go text search, torznab is the much better option.

**Comment by yiiTT** [comment]
yup "once elastic search is stable and bug-free" the search will really improve and then we can take a good look at implementing the torznab api.
