### ISSUE TITLE
Torrent Title instead of Hash for Torrent File Name.

### ISSUE THREAD

**Issue by printabcx** [NyaaPantsu/nyaa#736]
For organization sake, will there be plans to change the naming system for torrent files to the title of the torrent rather than naming it with it's hash?

**Comment by loadletter** [comment]
It could be easily done by adding a download attribute to the link, but it won't work on Firefox because torrents are stored on a different domain.

**Comment by printabcx** [comment]
> It could be easily done by adding a download attribute to the link, but it won't work on Firefox because torrents are stored on a different domain.

Not sure what it means. I'm just an ordinary user, so I don't know jargon related to developers. Could you elaborate on the attribute thing with the link with Firefox?

**Comment by loadletter** [comment]
I'm not a developer, it's just a suggestion because I had to deal with it, basically you can make a download link on a page download with a different name (which means no changes needed to existing torrents or torrent serving infrastructure) but firefox disallows this if the page with the link and the .torrent file are on different domains because of security implications.
