### ISSUE TITLE
Redesign / ES new dev issues

### ISSUE THREAD

**Issue by tomleb** [NyaaPantsu/nyaa#755]
I'll list the issues people find on the dev environment here:
- ~~ES search sorts on ID's by default (Looks like postgresql search sorts by date by default, to investigate)~~
- ~~No more explosssiiiioonnnnn (need to be added)~~ (#757) 
- ~~Wrong color of alternating row when the torrent is APlus, Trusted, etc.~~

- ~~Mobile needs a search bar~~
- ~~Theme defaults back when searching or changing order. (Whenever we load a new page)~~
- ~~Search button becomes invisible on tomorrow.~~
- ~~"The buttons aren't consistent widths. E.g. The "1" button is thinner than the "10" button. Which makes them crammed together and look janky." (Should probably make a fixed width for the pagination button)~~
- ~~Above wanted, current is bottom [pic](https://my.mixtape.moe/ugjjlv.png)~~
- Search puts a '*' when empty search
- Search box size and font size is small
- Date and time in torrent info has the time cut off due to the short column.
- Need wrapping of long character comments
- Icons are very hard to see on mobile using the /g/ theme.
- Z-index on the mascots is blocking the menu in small width views
- Edit torrent button is missing
- ES search seems to have worse performance than my 4gb machine :') (Getting queries of 70 ms instead of ~9 ms)
- Make /g/ Anon default theme (discuss)
- Duplicated comments See [https://nyaa.pantsu.cat/view/865002](https://nyaa.pantsu.cat/view/865002)
- Improvement to torrent view ?
- Duplication of lots of torrents (Might be ES related ?) (Multiple entries in db confirmed, need to check upload verification asap)
- "Invalid date" in comments

**Comment by nakedloli** [comment]
the "nyaapasu" and "explosion!" sounds are missing when you click on the mascot

**Comment by nevertrending** [comment]
<img width="1321" alt="screen shot 2017-05-26 at 03 40 42" src="https://cloud.githubusercontent.com/assets/11491360/26477363/6c4a9596-41c5-11e7-90c0-456c4bb2bd9e.png">
You should look into alignment of Magnet icon when the torrent is missing

**Comment by sfan5** [comment]
It takes a few seconds until absence of ES is detected:
<pre>
ERRO[0409] Unable to create elasticsearch client: health check timeout: no Elasticsearch node available 
ERRO[0409] Falling back to postgresql query             
INFO[0409] SQL query is :: 
</pre>

**Comment by sfan5** [comment]
* Date is cut off on view page
![bildschirmfoto_2017-05-26_17-42-27](https://cloud.githubusercontent.com/assets/1042418/26501759/c4aac3b2-423a-11e7-8e3c-188ed970e43a.png)

**Comment by printabcx** [comment]
The web design looked way better a few days ago. Then today happened... The layout was better than nyaa.si in terms of how information was displayed for any one specific torrent. Now it's just, I don't know...

The faceless loli vector was kind of unnecessary; now it's bigger. Honestly, I'd prefer a white background - there's just too much going on. The toggle option for day and night was a great feature. Really liked how the dark background, green outline, and purple buttons went with it, but now it's gone too. I swear, the best things are being stripped and replaced with tacky stuff. WTH is going on? I know the sites under development, but seriously, the progress seems to be backtracking. A change for pantsu/sukebei home icon should be differentiated to make it easier to tell which side we're on. Would be a bonus if the current pantsu icon was a bit more professional. You can even center the 6 jap characters to match the change in colours with the English on top.

All just suggestions. Feel free to ignore them. But honestly, I think it'd be better, since I want pantsu to overtake nyaa.si.

**Comment by sfan5** [comment]
I preferred the old design too, but it seems everyone else agreed that we definitely needed a redesign.
I also don't know why this new design was deployed before it has been thoroughly tested...

* "Show more torrents" button layout is completely broken
* table column (except date) is missing `border-bottom`
![bildschirmfoto_2017-05-27_11-02-19](https://cloud.githubusercontent.com/assets/1042418/26520086/2f0fe368-42cc-11e7-809d-f26ead1e752b.png)
* last scrape is not being displayed as a date correctly
![bildschirmfoto_2017-05-27_11-04-12]
(https://cloud.githubusercontent.com/assets/1042418/26520093/4630baf4-42cc-11e7-8d6f-5bcb66995a5d.png)
* everything is kinda too narrow IMO, the title column should be longer
* search bar moves if you activate your profile dropdown
* magnet/dl buttons on view page are still missing icons
* markdown editor bg is white in night mode
* would be nice if seeders/leechers/completed on view page was formatted as green/red/bold
* profile settings page is maximum ugly, why is everything centered?
* all buttons except "reset api key" on profile settings page are unstyled
* everything is broken in the modpanel (because it still relies on bootstrap & jquery)

**Comment by kipukun** [comment]
I can't agree that the old design was better in any regard. Man, especially the torrent view page. That was just gross. Which is why when I proposed a rework/redesign, most agreed. 
The thing is, nobody is trying to overtake nyaasi. The whole point of having multiple sites is for decentralization, as to not have another situation like we did with the late nyaa. I'm in no way trying to be "better" than nyaasi, since tribalism is dumb, especially with something as not serious as illegal Chinese cartoons. 
Also regarding professionalism; what's wrong with having fun with this project? I see no issue with adding fun things that, if you don't like, you can turn off. Possibly we could turn off the mascot by default, so you choose to opt-in rather than opt-out. I do appreciate your feedback though. More minds are always better.
Regarding all of sfan5's issues, I don't know why it was pushed to prod. Still needed a lot more rounding out. All are simple fixes though, and should be done soon :)

**Comment by printabcx** [comment]
> I can't agree that the old design was better in any regard. Man, especially the torrent view page. That was just gross. Which is why when I proposed a rework/redesign, most agreed.
The thing is, nobody is trying to overtake nyaasi. The whole point of having multiple sites is for decentralization, as to not have another situation like we did with the late nyaa. I'm in no way trying to be "better" than nyaasi, since tribalism is dumb, especially with something as not serious as illegal Chinese cartoons.
Also regarding professionalism; what's wrong with having fun with this project? I see no issue with adding fun things that, if you don't like, you can turn off. Possibly we could turn off the mascot by default, so you choose to opt-in rather than opt-out. I do appreciate your feedback though. More minds are always better.
Regarding all of sfan5's issues, I don't know why it was pushed to prod. Still needed a lot more rounding out. All are simple fixes though, and should be done soon :)

I enjoyed the thoughts you had in your reply. Continue what you're doing then. Hope to continue to see the ever-improving nyaa pantsu.

**Comment by printabcx** [comment]
Any chance that there will be a change with the torrent files being the title of the torrent and not its hash?

**Comment by kipukun** [comment]
@printabcx, you can ask @sfan5 about that

**Comment by sfan5** [comment]
Uhh, that would definitely be possible, but storing torrents using their intohash makes things a lot easier.
Filename could be done by overwriting the HTTP header I guess.

**Comment by printabcx** [comment]
@sfan5 From the perspective of a user, I think it's easier to organize themselves. Is there a way that it would be easier for both the developers and users?

@kipukun I really like the small icons like the floppy disc (save torrent file), and magnet (magnet link) and are really meaningful. Are those icons used from developer tools? They certainly not images.

**Comment by kipukun** [comment]
@printabcx They're icons from font awesome converted into base64 images (since I don't want to use CSS). Though, I am considering making SVGs as they scale better on mobile

**Comment by printabcx** [comment]
@kipukun They look great on the browse sections of pantsu.

**Comment by kipukun** [comment]
@printabcx Thanks!

**Comment by sfan5** [comment]
* ![](https://my.mixtape.moe/nbmzhh.png)
* `/settings` page is pretty ugly
* Mascot button loses it's translation when you click it

**Comment by sfan5** [comment]
* mod bar buttons need styling
* "save changes" button moves into line below
* modpanel tables are missing margins
* modpanel delete buttons should be red
* generally some coloring for buttons would be nice (dl/magnet -> green, edit -> yellow)
* text doesn't fit in modpanel
![](https://my.mixtape.moe/dhgzqp.png)
* reassign form looks ugly (elements shouldn't be centered)
* reassign form textarea should have `rows="20" cols="40"`
