### ISSUE TITLE
preserve theme choice across nyaa and subeki

### ISSUE THREAD

**Issue by solinium** [NyaaPantsu/nyaa#836]
for example, if you have dark theme on, it can be uncomfortable to go to subeki and be blasted with light (lol)

**Comment by steindornatorinn** [comment]
This is already implemented for signed in users, and just waiting to be pushed to production. However, the Domain property in the cookie header seems not to be configured so this will still be a issue for anonymous users.

**Comment by egozi44** [comment]
You should also add better theme, I  sort of hate that white, look too simple and too clear in the wrong way (for my taste), I honestly think that if you copy-paste the old nyaa's style no one will complain but I assume that since you use Go it won't look the same anyway.... still any color that is not simple black and white will do.

I also suggest change the background icon character from Non Non Biyori to something like Rias Gremory from DXD (you can find it in similar style to the Non Non Biyori character in the net) only in sukebei to fit the site's theme.


One last suggestion that have nothing to do with the site theme will be to sort of work together or at least share some trackers with the other nyaa (nyaa.si) so that we have more seeders, I don't know what your terms with the other site's crew but I do know that after what happened to the cat we all should know better by now that it not good idea to upload anything just to one site, cause once it down for whatever reason.... we screwed

**Comment by egozi44** [comment]
Oh also, any plans to add back the j-list ads? unless you want the site ads free that it, J-list ads was... sort of, comfortable in the eye and filled up the empty spaces of the site, they also not were that annoy imo especially after they made them smaller.

**Comment by tomleb** [comment]
> I honestly think that if you copy-paste the old nyaa's style no one will complain but I assume that since you use Go it won't look the same anyway.... 
The programming language has nothing to do with it.
> Oh also, any plans to add back the j-list ads?
No, if the site becomes too much costly we will go with donation instead and then if that doesn't work (which is unlikely, but still) we will use ads.

**Comment by akuma06** [comment]
Can't we add an opt-in option for registered users to enable J-List adds?

**Comment by steindornatorinn** [comment]
I'm sorry, I just can't see ads as a feature. If they are opt-in they will also generate hilariously little revenue. Plus someone at some point said "no ads" and this feature will never be worth the drama breaking that promise will cause.

**Comment by akuma06** [comment]
Or can't we make fake J-List ads. Not an ad but you still get the cool images

**Comment by steindornatorinn** [comment]
Brilliant idea, I'll start working on it right away!

**Comment by alucard0134** [comment]
We do not intend on using ads at all. I am not sure what notion made @tomleb say otherwise.
