### ISSUE TITLE
Fap link disappears in some languages

### ISSUE THREAD

**Issue by MMP0** [NyaaPantsu/nyaa#915]
![tes](https://cloud.githubusercontent.com/assets/28616020/26763392/2997ef30-498d-11e7-9c58-725e0e0f49fe.PNG)

**Comment by steindornatorinn** [comment]
The problem here is just that the header is overcrowded at the moment.

I want to do one ore more of the following:
Replace the RSS link with the RSS button at all window sizes.
Put the results per page somewhere else, make it a cookie setting or some sort of "advanced search" feature. It doesn't really belong on the navbar.
Remove avatars from the navbar, they aren't really needed there.
Move the FAQ somewhere else, since it is the biggest source of language settings breaking the navbar. It's really hard to deal with a 3 letter word becoming something like "Preguntas frequentes" when we are already starved for space.

**Comment by akuma06** [comment]
The navbar has more space now, so it is no more an issue
